export const CATEGORIES = ["all", "burger", "combo", "pizza", "sides", "drinks"];

export const CATEGORY_LABELS = {
  uk: { all: "Усе меню", burger: "Бургери", combo: "Комбо", pizza: "Піца", sides: "Закуски", drinks: "Напої" },
  sk: { all: "Celé menu", burger: "Burgery", combo: "Kombá", pizza: "Pizza", sides: "Prílohy", drinks: "Nápoje" },
};

export const DEFAULT_PRODUCTS = [
  { id: "quadro-burger", category: "burger", name_uk: "Квадро Бургер", name_sk: "Quadro Burger", description_uk: "Дві яловичі котлети, подвійний чедер, бекон, огірок, цибуля та фірмовий соус.", description_sk: "Dve hovädzie placky, dvojitý čedar, slanina, uhorka, cibuľa a náš domáci dresing.", price_cents: 1290, emoji: "🍔", badge_uk: "Фірмовий", badge_sk: "Signature", active: true, sort_order: 10 },
  { id: "classic-cheese", category: "burger", name_uk: "Класік Чіз", name_sk: "Classic Cheese", description_uk: "Яловичина, чедер, салат, помідор, маринований огірок і бургер-соус.", description_sk: "Hovädzie mäso, čedar, šalát, paradajka, nakladaná uhorka a burgerový dresing.", price_cents: 890, emoji: "🍔", badge_uk: "Хіт", badge_sk: "Hit", active: true, sort_order: 20 },
  { id: "chicken-crunch", category: "burger", name_uk: "Чікен Кранч", name_sk: "Chicken Crunch", description_uk: "Хрустке курча, чедер, салат, огірок і медово-гірчичний соус.", description_sk: "Chrumkavé kurča, čedar, šalát, uhorka a medovo-horčicový dresing.", price_cents: 990, emoji: "🍗", badge_uk: "", badge_sk: "", active: true, sort_order: 30 },
  { id: "veggie-burger", category: "burger", name_uk: "Грін Бургер", name_sk: "Green Burger", description_uk: "Овочева котлета, чедер, рукола, помідор, цибуля та соус айвар.", description_sk: "Zeleninová placka, čedar, rukola, paradajka, cibuľa a ajvar dresing.", price_cents: 940, emoji: "🥬", badge_uk: "Без м'яса", badge_sk: "Bez mäsa", active: true, sort_order: 40 },
  { id: "quad-menu", category: "combo", name_uk: "Квадро Меню", name_sk: "Quadro Menu", description_uk: "Квадро Бургер, велика картопля фрі, соус та напій 0,5 л.", description_sk: "Quadro Burger, veľké hranolky, omáčka a nápoj 0,5 l.", price_cents: 1590, emoji: "🍔", badge_uk: "Найвигідніше", badge_sk: "Top ponuka", active: true, sort_order: 50 },
  { id: "classic-menu", category: "combo", name_uk: "Класік Меню", name_sk: "Classic Menu", description_uk: "Класік Чіз, картопля фрі, соус та напій 0,5 л.", description_sk: "Classic Cheese, hranolky, omáčka a nápoj 0,5 l.", price_cents: 1290, emoji: "🍟", badge_uk: "", badge_sk: "", active: true, sort_order: 60 },
  { id: "chicken-menu", category: "combo", name_uk: "Чікен Меню", name_sk: "Chicken Menu", description_uk: "Чікен Кранч, картопля фрі, соус та напій 0,5 л.", description_sk: "Chicken Crunch, hranolky, omáčka a nápoj 0,5 l.", price_cents: 1390, emoji: "🥤", badge_uk: "", badge_sk: "", active: true, sort_order: 70 },
  { id: "pizza-margherita", category: "pizza", name_uk: "Маргарита", name_sk: "Margherita", description_uk: "Томатний соус, моцарела, базилік та оливкова олія. 33 см.", description_sk: "Paradajková omáčka, mozzarella, bazalka a olivový olej. 33 cm.", price_cents: 890, emoji: "🍕", badge_uk: "", badge_sk: "", active: true, sort_order: 80 },
  { id: "pizza-pepperoni", category: "pizza", name_uk: "Пепероні", name_sk: "Pepperoni", description_uk: "Томатний соус, моцарела та пікантна салямі. 33 см.", description_sk: "Paradajková omáčka, mozzarella a pikantná saláma. 33 cm.", price_cents: 1090, emoji: "🍕", badge_uk: "Хіт", badge_sk: "Hit", active: true, sort_order: 90 },
  { id: "pizza-quattro", category: "pizza", name_uk: "Кватро Формаджі", name_sk: "Quattro Formaggi", description_uk: "Моцарела, горгонзола, пармезан та копчений сир. 33 см.", description_sk: "Mozzarella, gorgonzola, parmezán a údený syr. 33 cm.", price_cents: 1150, emoji: "🧀", badge_uk: "", badge_sk: "", active: true, sort_order: 100 },
  { id: "pizza-diavola", category: "pizza", name_uk: "Діавола", name_sk: "Diavola", description_uk: "Томатний соус, моцарела, гостра салямі, чилі та цибуля. 33 см.", description_sk: "Paradajková omáčka, mozzarella, pikantná saláma, chilli a cibuľa. 33 cm.", price_cents: 1150, emoji: "🌶️", badge_uk: "Гостра", badge_sk: "Pikantná", active: true, sort_order: 110 },
  { id: "fries", category: "sides", name_uk: "Картопля фрі", name_sk: "Hranolky", description_uk: "Подвійно обсмажена картопля з копченою паприкою.", description_sk: "Dvakrát vyprážané hranolky s údenou paprikou.", price_cents: 320, emoji: "🍟", badge_uk: "", badge_sk: "", active: true, sort_order: 120 },
  { id: "loaded-fries", category: "sides", name_uk: "Чедер Фрі", name_sk: "Cheddar Fries", description_uk: "Картопля фрі, чедерний соус, бекон і хрустка цибуля.", description_sk: "Hranolky, čedarová omáčka, slanina a chrumkavá cibuľka.", price_cents: 690, emoji: "🧀", badge_uk: "", badge_sk: "", active: true, sort_order: 130 },
  { id: "onion-rings", category: "sides", name_uk: "Цибулеві кільця", name_sk: "Cibuľové krúžky", description_uk: "Хрусткі цибулеві кільця з домашнім соусом.", description_sk: "Chrumkavé cibuľové krúžky s domácou omáčkou.", price_cents: 390, emoji: "🧅", badge_uk: "", badge_sk: "", active: true, sort_order: 140 },
  { id: "kofola", category: "drinks", name_uk: "Kofola 0,5 л", name_sk: "Kofola 0,5 l", description_uk: "Охолоджена Kofola Original.", description_sk: "Vychladená Kofola Original.", price_cents: 240, emoji: "🥤", badge_uk: "", badge_sk: "", active: true, sort_order: 150 },
  { id: "cola", category: "drinks", name_uk: "Coca-Cola 0,5 л", name_sk: "Coca-Cola 0,5 l", description_uk: "Original або Zero — вкажіть у коментарі.", description_sk: "Original alebo Zero — uveďte v poznámke.", price_cents: 240, emoji: "🥤", badge_uk: "", badge_sk: "", active: true, sort_order: 160 },
  { id: "lemonade", category: "drinks", name_uk: "Домашній лимонад", name_sk: "Domáca limonáda", description_uk: "Лимон, лайм, м'ята та содова. 0,4 л.", description_sk: "Citrón, limetka, mäta a sóda. 0,4 l.", price_cents: 320, emoji: "🍋", badge_uk: "", badge_sk: "", active: true, sort_order: 170 },
  { id: "water", category: "drinks", name_uk: "Мінеральна вода", name_sk: "Minerálna voda", description_uk: "Газована або негазована. 0,5 л.", description_sk: "Sýtená alebo nesýtená. 0,5 l.", price_cents: 190, emoji: "💧", badge_uk: "", badge_sk: "", active: true, sort_order: 180 },
];

export const TRANSLATIONS = {
  uk: {
    notice: "Безкоштовна доставка від 30 €", hoursShort: "Щодня 11:00–22:00", menu: "Меню", delivery: "Доставка", contacts: "Контакти", cart: "Кошик",
    heroEyebrow: "Справжній смак Братислави", heroTitle: "ВЕЛИКИЙ СМАК.<br /><em>ЧЕСНІ</em> БУРГЕРИ.", heroText: "Соковиті бургери, хрустка картопля, гаряча піца та комбо, які хочеться повторити.", chooseMenu: "Обрати меню", rating: "оцінка гостей", from: "від", combo: "комбо", freshDaily: "Свіже<br />щодня",
    benefitOneTitle: "Готуємо після замовлення", benefitOneText: "Нічого не лежить під лампою", benefitTwoTitle: "Доставка 35–50 хв", benefitTwoText: "По Братиславі та поруч", benefitThreeTitle: "Оплата при отриманні", benefitThreeText: "Готівкою або карткою кур'єру",
    ourMenu: "Наше меню", menuTitle: "ОБЕРИ СВІЙ<br /><em>ІДЕАЛЬНИЙ</em> СМАК", menuIntro: "Ціни підібрані відповідно до актуального рівня закладів Братислави. Склад і ціни адміністратор може оновлювати будь-коли.",
    signature: "Фірмове комбо", quadComboTitle: "КВАДРО МЕНЮ —<br />УСЕ, ЩО ТРЕБА.", quadComboText: "Подвійний бургер, велика картопля, соус і напій 0,5 л.", addFor: "Додати за 15,90 €",
    howItWorks: "Як це працює", deliveryTitle: "ВІД КЛІКУ ДО<br /><em>ПЕРШОГО</em> УКУСУ", stepOneTitle: "Обери страви", stepOneText: "Додай у кошик усе, що хочеться сьогодні.", stepTwoTitle: "Вкажи контакти", stepTwoText: "Телефон, спосіб отримання та адресу.", stepThreeTitle: "Ми підтвердимо", stepThreeText: "Замовлення потрапить закладу й на пошту.",
    schedule: "Графік", hours: "Щодня, 11:00–22:00", area: "Зона доставки", phone: "Телефон", comingSoon: "буде додано", yourOrder: "Ваше замовлення", emptyTitle: "Тут поки порожньо", emptyText: "Додайте бургер, піцу або комбо з меню.", toMenu: "До меню", checkout: "Оформлення", deliveryOption: "Доставка", pickupOption: "Самовивіз", name: "Ім'я", address: "Адреса доставки", note: "Коментар", subtotal: "Сума", deliveryFee: "Доставка", total: "Разом", placeOrder: "Підтвердити замовлення", orderLegal: "Натискаючи кнопку, ви погоджуєтесь на обробку даних для виконання замовлення.", successTitle: "Замовлення прийнято!", done: "Готово",
    added: "Додано до кошика", backendPending: "Онлайн-замовлення буде активоване після додавання пошти закладу. Кошик уже працює.", orderError: "Не вдалося надіслати замовлення. Спробуйте ще раз.", orderSuccess: "Номер замовлення: {code}. Ми зв'яжемося з вами для підтвердження.", free: "безкоштовно",
    viewSite: "Переглянути сайт ↗", logout: "Вийти", setup: "Підготовка", setupTitle: "Адмін-панель готова до підключення", setupText: "Інтерфейс, база та захист створені. Після додавання адреси пошти й ключів Supabase тут з'явиться безпечний вхід адміністратора.", adminOnly: "Тільки для адміністратора", adminLogin: "Вхід до керування", adminLoginText: "Увійдіть через обліковий запис, який має права адміністратора.", password: "Пароль", login: "Увійти", management: "Керування закладом", dashboardTitle: "Меню та замовлення", dashboardText: "Зміни не побачать відвідувачі, доки ви не натиснете «Опублікувати».", publish: "Опублікувати зміни", products: "Товари", orders: "Замовлення", catalog: "Каталог", catalogHint: "Додавайте, редагуйте та приховуйте позиції.", addProduct: "Додати товар", ordersHint: "Нові замовлення та їхній поточний статус.", refresh: "Оновити", loginError: "Неправильний email або пароль, або цей акаунт не є адміністратором.", publishSuccess: "Зміни опубліковано — відвідувачі вже бачать нове меню.", publishError: "Не вдалося опублікувати зміни.", noOrders: "Замовлень поки немає.", productNameUk: "Назва UA", productNameSk: "Назва SK", description: "Опис", category: "Категорія", price: "Ціна €", active: "На сайті", newProduct: "Новий товар", statusNew: "Нове", statusConfirmed: "Підтверджено", statusPreparing: "Готується", statusReady: "Готове", statusDelivered: "Виконано", statusCancelled: "Скасовано"
  },
  sk: {
    notice: "Doprava zadarmo od 30 €", hoursShort: "Denne 11:00–22:00", menu: "Menu", delivery: "Dovoz", contacts: "Kontakt", cart: "Košík",
    heroEyebrow: "Pravá chuť Bratislavy", heroTitle: "VEĽKÁ CHUŤ.<br /><em>POCTIVÉ</em> BURGERY.", heroText: "Šťavnaté burgery, chrumkavé hranolky, horúca pizza a kombá, ku ktorým sa radi vrátite.", chooseMenu: "Vybrať si menu", rating: "hodnotenie hostí", from: "od", combo: "kombo", freshDaily: "Čerstvé<br />každý deň",
    benefitOneTitle: "Varíme až po objednaní", benefitOneText: "Nič nečaká pod lampou", benefitTwoTitle: "Dovoz 35–50 min", benefitTwoText: "Bratislava a okolie", benefitThreeTitle: "Platba pri prevzatí", benefitThreeText: "Hotovosť alebo karta kuriérovi",
    ourMenu: "Naše menu", menuTitle: "VYBER SI SVOJU<br /><em>IDEÁLNU</em> CHUŤ", menuIntro: "Ceny zodpovedajú aktuálnej úrovni prevádzok v Bratislave. Ponuku aj ceny môže správca kedykoľvek upraviť.",
    signature: "Signature kombo", quadComboTitle: "QUADRO MENU —<br />VŠETKO, ČO TREBA.", quadComboText: "Dvojitý burger, veľké hranolky, omáčka a nápoj 0,5 l.", addFor: "Pridať za 15,90 €",
    howItWorks: "Ako to funguje", deliveryTitle: "OD KLIKNUTIA PO<br /><em>PRVÉ</em> SÚSTO", stepOneTitle: "Vyber si jedlo", stepOneText: "Pridaj do košíka všetko, na čo máš chuť.", stepTwoTitle: "Zadaj kontakt", stepTwoText: "Telefón, spôsob prevzatia a adresu.", stepThreeTitle: "Potvrdíme objednávku", stepThreeText: "Objednávka príde prevádzke aj na e-mail.",
    schedule: "Otváracie hodiny", hours: "Denne, 11:00–22:00", area: "Zóna rozvozu", phone: "Telefón", comingSoon: "doplníme", yourOrder: "Vaša objednávka", emptyTitle: "Zatiaľ je tu prázdno", emptyText: "Pridajte si burger, pizzu alebo kombo z menu.", toMenu: "Prejsť na menu", checkout: "Objednávka", deliveryOption: "Dovoz", pickupOption: "Osobný odber", name: "Meno", address: "Adresa doručenia", note: "Poznámka", subtotal: "Medzisúčet", deliveryFee: "Dovoz", total: "Spolu", placeOrder: "Potvrdiť objednávku", orderLegal: "Kliknutím na tlačidlo súhlasíte so spracovaním údajov na vybavenie objednávky.", successTitle: "Objednávka prijatá!", done: "Hotovo",
    added: "Pridané do košíka", backendPending: "Online objednávky aktivujeme po doplnení e-mailu prevádzky. Košík už funguje.", orderError: "Objednávku sa nepodarilo odoslať. Skúste to znova.", orderSuccess: "Číslo objednávky: {code}. Ozveme sa vám s potvrdením.", free: "zadarmo",
    viewSite: "Zobraziť web ↗", logout: "Odhlásiť", setup: "Príprava", setupTitle: "Administrácia je pripravená na pripojenie", setupText: "Rozhranie, databáza aj zabezpečenie sú pripravené. Po doplnení e-mailu a kľúčov Supabase sa tu zobrazí bezpečné prihlásenie správcu.", adminOnly: "Len pre správcu", adminLogin: "Prihlásenie do správy", adminLoginText: "Prihláste sa účtom s oprávnením správcu.", password: "Heslo", login: "Prihlásiť", management: "Správa prevádzky", dashboardTitle: "Menu a objednávky", dashboardText: "Návštevníci zmeny neuvidia, kým nestlačíte „Publikovať“.", publish: "Publikovať zmeny", products: "Produkty", orders: "Objednávky", catalog: "Katalóg", catalogHint: "Pridávajte, upravujte alebo skrývajte položky.", addProduct: "Pridať produkt", ordersHint: "Nové objednávky a ich aktuálny stav.", refresh: "Obnoviť", loginError: "Nesprávny e-mail alebo heslo, prípadne účet nemá práva správcu.", publishSuccess: "Zmeny sú publikované — návštevníci už vidia nové menu.", publishError: "Zmeny sa nepodarilo publikovať.", noOrders: "Zatiaľ nemáte žiadne objednávky.", productNameUk: "Názov UA", productNameSk: "Názov SK", description: "Popis", category: "Kategória", price: "Cena €", active: "Na webe", newProduct: "Nový produkt", statusNew: "Nová", statusConfirmed: "Potvrdená", statusPreparing: "Pripravuje sa", statusReady: "Pripravená", statusDelivered: "Vybavená", statusCancelled: "Zrušená"
  }
};

export function productName(product, locale) { return product[`name_${locale}`] || product.name_uk || ""; }
export function productDescription(product, locale) { return product[`description_${locale}`] || product.description_uk || ""; }
export function productBadge(product, locale) { return product[`badge_${locale}`] || ""; }
export function formatPrice(cents) { return new Intl.NumberFormat("sk-SK", { style: "currency", currency: "EUR" }).format((Number(cents) || 0) / 100); }
